<a href="https://colab.research.google.com/github/MonowarHusain/CSE424/blob/main/lab/lab01/Pandas_for_ML_Tabular_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
#from google.colab import drive
#drive.mount('/content/drive')

In [43]:
import pandas as pd
import numpy as np

homelessness = pd.read_csv("https://raw.githubusercontent.com/labib15/Machine-Learning-Datasets/main/homelessness.csv")  #reading a csv file into a dataframe named homelessness
volunteer = pd.read_csv("https://raw.githubusercontent.com/labib15/Machine-Learning-Datasets/main/volunteer_opportunities.csv")
sales = pd.read_csv('https://raw.githubusercontent.com/labib15/Machine-Learning-Datasets/main/sales.csv')
hiking = pd.read_json('https://raw.githubusercontent.com/labib15/Machine-Learning-Datasets/main/hiking.json')
#wards = pd.read_csv("/content/drive/MyDrive/U   N   I/Machine Learning/Code/Dataset/wards.csv",delimiter = ",")

## Checking the Dataframe


```
1. head(no. of rows) = Shows the selected no. of rows/ samples in the dataframe from the BEGINNING. Default: 5
2. tail(no. of rows) = Shows the selected no. of rows / samples in the dataframe from the END.  Default: 5
3. shape = row and column number
4. columns = name of columns
5. info() = data type of each column
6. describe() = mean, median, std, etc info about each column
7. values = values in the 2d list.
8. value_counts() = number of each type in a particular column
```

In [44]:
homelessness.head() #show the first 5 rows

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588

In [45]:
homelessness.head(10)   #shows the first 10 rows

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588
5,5,Mountain,Colorado,7607.0,3250.0,5691287
6,6,New England,Connecticut,2280.0,1696.0,3571520
7,7,South Atlantic,Delaware,708.0,374.0,965479
8,8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,9,South Atlantic,Florida,21443.0,9587.0,21244317

In [46]:
homelessness.tail()

,Unnamed: 0,region,state,individuals,family_members,state_pop
46,46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,47,Pacific,Washington,16424.0,5880.0,7523869
48,48,South Atlantic,West Virginia,1021.0,222.0,1804291
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
50,50,Mountain,Wyoming,434.0,205.0,577601

In [47]:
homelessness.tail(10)

,Unnamed: 0,region,state,individuals,family_members,state_pop
41,41,West North Central,South Dakota,836.0,323.0,878698
42,42,East South Central,Tennessee,6139.0,1744.0,6771631
43,43,West South Central,Texas,19199.0,6111.0,28628666
44,44,Mountain,Utah,1904.0,972.0,3153550
45,45,New England,Vermont,780.0,511.0,624358
46,46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,47,Pacific,Washington,16424.0,5880.0,7523869
48,48,South Atlantic,West Virginia,1021.0,222.0,1804291
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
50,50,Mountain,Wyoming,434.0,205.0,577601

In [48]:
print(homelessness.shape)
print(homelessness.columns)

(51, 6)
Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='object')

In [49]:
print(homelessness.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      51 non-null     int64
 1   region          51 non-null     object
 2   state           51 non-null     object
 3   individuals     51 non-null     float64
 4   family_members  51 non-null     float64
 5   state_pop       51 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 2.5+ KB
None

In [50]:
print(homelessness.describe())

       Unnamed: 0    individuals  family_members     state_pop
count   51.000000      51.000000       51.000000  5.100000e+01
mean    25.000000    7225.784314     3504.882353  6.405637e+06
std     14.866069   15991.025083     7805.411811  7.327258e+06
min      0.000000     434.000000       75.000000  5.776010e+05
25%     12.500000    1446.500000      592.000000  1.777414e+06
50%     25.000000    3082.000000     1482.000000  4.461153e+06
75%     37.500000    6781.500000     3196.000000  7.340946e+06
max     50.000000  109008.000000    52070.000000  3.946159e+07

## Subsetting Columns/Features

In [51]:
#Subsetting one column
r = homelessness[["region"]]
r.head()

               region
0  East South Central
1             Pacific
2            Mountain
3  West South Central
4             Pacific

In [52]:
#Subsetting multiple columns
r_f = homelessness[["region","family_members"]]
r_f.head()

               region  family_members
0  East South Central           864.0
1             Pacific           582.0
2            Mountain          2606.0
3  West South Central           432.0
4             Pacific         20964.0

### **value_counts()**  --> Used to give count for each values for a specified column

In [53]:
homelessness["region"].value_counts()

region
South Atlantic        9
Mountain              8
West North Central    7
New England           6
East North Central    5
Pacific               5
East South Central    4
West South Central    4
Mid-Atlantic          3
Name: count, dtype: int64

In [54]:
homelessness["region"].value_counts(ascending = False)  #ascending = True (default)

region
South Atlantic        9
Mountain              8
West North Central    7
New England           6
East North Central    5
Pacific               5
East South Central    4
West South Central    4
Mid-Atlantic          3
Name: count, dtype: int64

In [55]:
homelessness["region"].value_counts(normalize = True) #normalize = False (default).

region
South Atlantic        0.176471
Mountain              0.156863
West North Central    0.137255
New England           0.117647
East North Central    0.098039
Pacific               0.098039
East South Central    0.078431
West South Central    0.078431
Mid-Atlantic          0.058824
Name: proportion, dtype: float64

## Subsetting Rows

**Comparison Operation**

In [56]:
fam_less_than_1k_boolean = homelessness["family_members"]<1000
fam_less_than_1k_boolean.head()

0     True
1     True
2    False
3     True
4    False
Name: family_members, dtype: bool

In [57]:
fam_less_than_1k = homelessness[homelessness["family_members"]<1000]
fam_less_than_1k.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
3,3,West South Central,Arkansas,2280.0,432.0,3009733
7,7,South Atlantic,Delaware,708.0,374.0,965479
12,12,Mountain,Idaho,1297.0,715.0,1750536

In [58]:
mountain_reg = homelessness[homelessness["region"]=="Mountain"]
mountain_reg.head()

    Unnamed: 0    region     state  individuals  family_members  state_pop
2            2  Mountain   Arizona       7259.0          2606.0    7158024
5            5  Mountain  Colorado       7607.0          3250.0    5691287
12          12  Mountain     Idaho       1297.0           715.0    1750536
26          26  Mountain   Montana        983.0           422.0    1060665
28          28  Mountain    Nevada       7058.0           486.0    3027341

In [59]:
not_mountain_reg = homelessness[homelessness["region"]!="Mountain"]
not_mountain_reg.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588
6,6,New England,Connecticut,2280.0,1696.0,3571520

**Logical Operator**

In [60]:
fam_and_reg = homelessness[(homelessness["family_members"]<1000) & (homelessness["region"]=="Mountain")]
fam_and_reg.head()

    Unnamed: 0    region       state  individuals  family_members  state_pop
12          12  Mountain       Idaho       1297.0           715.0    1750536
26          26  Mountain     Montana        983.0           422.0    1060665
28          28  Mountain      Nevada       7058.0           486.0    3027341
31          31  Mountain  New Mexico       1949.0           602.0    2092741
44          44  Mountain        Utah       1904.0           972.0    3153550

In [61]:
fam_or_reg = homelessness[(homelessness["family_members"]<1000) | (homelessness["region"]=="Mountain")]
fam_or_reg.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
5,5,Mountain,Colorado,7607.0,3250.0,5691287

In [62]:
reg_or= homelessness[homelessness["region"].isin(["Mountain","Pacific"])]
reg_or.head()

    Unnamed: 0    region       state  individuals  family_members  state_pop
1            1   Pacific      Alaska       1434.0           582.0     735139
2            2  Mountain     Arizona       7259.0          2606.0    7158024
4            4   Pacific  California     109008.0         20964.0   39461588
5            5  Mountain    Colorado       7607.0          3250.0    5691287
11          11   Pacific      Hawaii       4131.0          2399.0    1420593

## Adding New Columns

In [63]:
homelessness.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588

In [64]:
homelessness["total"] = homelessness["individuals"] + homelessness["family_members"]
homelessness.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop,total
0,0,East South Central,Alabama,2570.0,864.0,4887681,3434.0
1,1,Pacific,Alaska,1434.0,582.0,735139,2016.0
2,2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0
3,3,West South Central,Arkansas,2280.0,432.0,3009733,2712.0
4,4,Pacific,California,109008.0,20964.0,39461588,129972.0

In [65]:
homelessness["p_individuals"] = homelessness["individuals"]/homelessness["total"]
homelessness.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop,total,p_individuals
0,0,East South Central,Alabama,2570.0,864.0,4887681,3434.0,0.748398
1,1,Pacific,Alaska,1434.0,582.0,735139,2016.0,0.711310
2,2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0,0.735834
3,3,West South Central,Arkansas,2280.0,432.0,3009733,2712.0,0.840708
4,4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.838704

## Checking Null Values





`Here we are taking a new dataframe called 'volunteer'`

In [66]:
volunteer.shape

(665, 35)

In [67]:
volunteer.head()

,opportunity_id,content_id,vol_requests,event_time,title,hits,summary,is_priority,category_id,category_desc,...,end_date_date,status,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,4996,37004,50,0,Volunteers Needed For Rise Up & Stay Put! Home...,737,Building on successful events last summer and ...,NaN,NaN,NaN,...,July 30 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5008,37036,2,0,Web designer,22,Build a website for an Afghan business,NaN,1.0,Strengthening Communities,...,February 01 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5016,37143,20,0,Urban Adventures - Ice Skating at Lasker Rink,62,Please join us and the students from Mott Hall...,NaN,1.0,Strengthening Communities,...,January 29 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5022,37237,500,0,Fight global hunger and support women farmers ...,14,The Oxfam Action Corps is a group of dedicated...,NaN,1.0,Strengthening Communities,...,March 31 2012,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5055,37425,15,0,Stop 'N' Swap,31,Stop 'N' Swap reduces NYC's waste by finding n...,NaN,4.0,Environment,...,February 05 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
volunteer.isnull()

,opportunity_id,content_id,vol_requests,event_time,title,hits,summary,is_priority,category_id,category_desc,...,end_date_date,status,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,False,False,False,False,False,False,False,True,True,True,...,False,False,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,True,True,True,True
661,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,True,True,True,True
662,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,True,True,True,True
663,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,True,True,True,True
664,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,True,True,True,True

In [69]:
volunteer.isnull().sum()  #We implement this to know how many null values are in each columns of the "volunteer" dataframe

opportunity_id          0
content_id              0
vol_requests            0
event_time              0
title                   0
hits                    0
summary                 0
is_priority           603
category_id            48
category_desc          48
amsl                  665
amsl_unit             665
org_title               0
org_content_id          0
addresses_count         0
locality               70
region                  0
postalcode              6
primary_loc           665
display_url             0
recurrence_type         0
hours                   0
created_date            0
last_modified_date      0
start_date_date         0
end_date_date           0
status                  0
Latitude              665
Longitude             665
Community Board       665
Community Council     665
Census Tract          665
BIN                   665
BBL                   665
NTA                   665
dtype: int64

In [70]:
volunteer["locality"].isnull()

0       True
1      False
2       True
3       True
4       True
       ...
660    False
661    False
662    False
663    False
664    False
Name: locality, Length: 665, dtype: bool

In [71]:
volunteer["locality"].isnull().sum()

np.int64(70)

---



---
#Handling null values:

---



---



## Way 1: Dropping Rows - The wrong way (Avoid this)

In [72]:
volunteer.shape

(665, 35)

In [73]:
new_volunteer = volunteer.dropna()

In [74]:
new_volunteer.shape

(0, 35)

In [75]:
volunteer.shape

(665, 35)

In [76]:
new_volunteer2 = volunteer["category_id"].dropna()
new_volunteer2.shape

(617,)




## Way 2: Dropping a desired column - Better Approach (Follow this)


[Pandas Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html)

`
.drop(columns = [column_name], inplace = False)
`


> columns ▶ names of the columns to drop given as list

> inplace ▶ false (default). Have to be set `true` if the column needed to be drop from original dataframe.

In [77]:
new_volunteer3 = volunteer.drop(columns = ['primary_loc'],inplace = True)  #inplace = False (by default), hence the column was not dropped from the original dataframe 'volunteer'

In [78]:
volunteer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 665 entries, 0 to 664
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   opportunity_id      665 non-null    int64
 1   content_id          665 non-null    int64
 2   vol_requests        665 non-null    int64
 3   event_time          665 non-null    int64
 4   title               665 non-null    object
 5   hits                665 non-null    int64
 6   summary             665 non-null    object
 7   is_priority         62 non-null     object
 8   category_id         617 non-null    float64
 9   category_desc       617 non-null    object
 10  amsl                0 non-null      float64
 11  amsl_unit           0 non-null      float64
 12  org_title           665 non-null    object
 13  org_content_id      665 non-null    int64
 14  addresses_count     665 non-null    int64
 15  locality            595 non-null    object
 16  region              665 non-null    object
 17  postalcode          659 non-null    float64
 18  display_url         665 non-null    object
 19  recurrence_type     665 non-null    object
 20  hours               665 non-null    int64
 21  created_date        665 non-null    object
 22  last_modified_date  665 non-null    object
 23  start_date_date     665 non-null    object
 24  end_date_date       665 non-null    object
 25  status              665 non-null    object
 26  Latitude            0 non-null      float64
 27  Longitude           0 non-null      float64
 28  Community Board     0 non-null      float64
 29  Community Council   0 non-null      float64
 30  Census Tract        0 non-null      float64
 31  BIN                 0 non-null      float64
 32  BBL                 0 non-null      float64
 33  NTA                 0 non-null      float64
dtypes: float64(12), int64(8), object(14)
memory usage: 176.8+ KB

In [79]:
new_volunteer3.info()

AttributeError: 'NoneType' object has no attribute 'info'

## Way 3: Imputing values instead of null values

### Option 1: Directly Assign a value of our choice





> Without inplace imputing

In [ ]:
volunteer["BIN"].isnull().sum()

In [ ]:
volunteer["BIN"].fillna(10)

In [ ]:
volunteer["BIN"].isnull().sum()  #the rows in "BIN" column still have null features.



> inplace imputing values (2 Ways)

In [ ]:
#volunteer["BIN"].fillna(10, inplace = True)

In [ ]:
#volunteer["BIN"] = volunteer["BIN"].fillna(10)

In [ ]:
volunteer["BIN"].isnull().sum()

### Option 2: Using SimpleImputer to estimate a value for null values using existing values in the column

In [ ]:
sales.head()

In [ ]:
sales['salt'].isnull().sum()

In [ ]:
from sklearn.impute import SimpleImputer

impute = SimpleImputer(missing_values=np.nan, strategy='mean')

impute.fit(sales[['salt']])

sales['salt'] = impute.transform(sales[['salt']])  #Here we are making sure it is inplace = True

In [ ]:
sales['salt'].isnull().sum()

# Handling Categorical / Text Data

There are two types of text data we might come across.


*   Nominal - Not ordered. Non Heirchical. No ranking of one above another. For eg. names of countries, places, foods.
*   Ordinal - Ordered. Heirchical. Ranking of one above another. For eg. True / False, Best/Average/Worst

### Option 1: Nominal (No Ranking)


`
One hot encoding
`

In [ ]:
volunteer['category_desc'].unique()

In [ ]:
# Transform the category_desc column
category_enc = pd.get_dummies(volunteer['category_desc'])

# Take a look at the encoded columns
category_enc.head()

### Option 2: Ordinal (Ranking)

In [ ]:
hiking.head()



> **Using LabelEncoder**

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Set up the LabelEncoder object
enc = LabelEncoder()

# Apply the encoding to the "Accessible" column
hiking['Accessible_enc'] = enc.fit_transform(hiking['Accessible'])   # Here we are not changing inplace

# Compare the two columns
print(hiking[['Accessible', 'Accessible_enc']].head())



> **Using map**

In [ ]:
hiking['Accessible'] = hiking['Accessible'].map({'Y':1,'N':0})

# Dropping column due to correlation

In [ ]:
from sklearn.datasets import load_wine

wine = load_wine()
wine_df = pd.DataFrame( wine['data'], columns=wine['feature_names'])

In [ ]:
wine_df.head()

In [ ]:
wine_corr = wine_df.corr()
wine_corr

In [ ]:
import seaborn as sns

sns.heatmap(wine_corr, cmap = 'YlGnBu')

In [ ]:
# Take a minute to find the column where the correlation value is greater than 0.75 at least twice
to_drop = 'flavanoids'

# Drop that column from the DataFrame
wine_df = wine_df.drop(columns = to_drop)

In [ ]:
wine_df.columns   #no 'flavanoids' column present



---


# Scaling or Normalization

## Why do we need to scale our data?
* If a feature’s variance is orders of magnitude more than the variance of other features, that particular feature might dominate other features in the dataset and make the estimator unable to learn from other features correctly, i.e. our learner might give more importance to features with high variance, which is not something we want happening in our model.

The following are a few different types of Scalers:

----


**MinMax Scaler:**

Scales values to a range between 0 and 1 if no negative values, and -1 to 1 if there are negative values present.

$$\frac{X - X_{min}}{X_{max} - X_{min}}$$

where,

 $$X\space is\space a\space feature\space value.$$
 $$X_{min} \space and \space X_{max} \space are \space corresponding \space feature's \space min \space and \space max \space values. $$


**Standard Scaler:**

$$\frac{X - mean}{\sigma}$$
where,
$$\sigma = standard \space deviation $$

**Robust Scaler:**

Uses statistics that are robust to outliers

$$\frac{X - median}{IQR}$$

where,

$$ IQR = Inter\space Quartile\space Range = Q_3 - Q_1 $$

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Load the breast cancer dataset
data_cancer = load_breast_cancer()
df = pd.DataFrame(data_cancer.data, columns=data_cancer.feature_names)

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(df)

# Create a new DataFrame with the scaled data
scaled_df = pd.DataFrame(scaled_data, columns=data.feature_names)

# Print the scaled DataFrame (optional)
print(scaled_df.head())

# Train-Test Split
[Sk-Learn Documentation](https://scikit-learn.org/1.5/modules/generated/sklearn.model_selection.train_test_split.html)

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

cancer = load_breast_cancer()

X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size = 0.20, stratify = cancer.target, random_state=1)

In [ ]:
# prompt: logistic regression using sklearn

from sklearn.linear_model import LogisticRegression

# Initialize the Logistic Regression model
log_reg = LogisticRegression()

# Train the model
log_reg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = log_reg.predict(X_test)

# Evaluate the model (example: accuracy)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

In [ ]:
# prompt: sklearn implementation of naive bayes

from sklearn.naive_bayes import GaussianNB

# Assuming X_train, X_test, y_train, y_test are already defined from the previous code

# Initialize the Gaussian Naive Bayes model
gnb = GaussianNB()

# Train the model
gnb.fit(X_train, y_train)

# Make predictions on the test set
y_pred_gnb = gnb.predict(X_test)

# Evaluate the model (example: accuracy)
accuracy_gnb = accuracy_score(y_test, y_pred_gnb)
print(f"Gaussian Naive Bayes Accuracy: {accuracy_gnb}")

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
print(f"Decision Tree Accuracy: {accuracy_dt}")

In [ ]:
# prompt: use the model random forest for the  same dataset

from sklearn.ensemble import RandomForestClassifier

# Assuming X_train, X_test, y_train, y_test are already defined from the previous code

# Initialize the Random Forest model
rf = RandomForestClassifier(n_estimators=100, random_state=1)

# Train the model
rf.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf = rf.predict(X_test)

# Evaluate the model (example: accuracy)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf}")